### ISSUE TITLE
Add loader animation and hide results until all addresses are processed

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#35]
The primary adjustments here are:
1. We should include the sitewide header and footer on all the pages (these comps include a version of the new one)
2. On the landing page, there should be a breadcrumb back to the policy and compliance page where the tool lives, and the page title should sit below that
3. The page title and breadcrumb should probably still be on the page for the results screen (I'm less sold on whether we *need* to do this, but it's a general best practice to keep the title on there and the comp below looks fine
4. Use a [loader animation](https://github.com/cfpb/design-manual/issues/227) and hide the results until everything is ready

![screen shot 2015-10-13 at 12 30 05 pm](https://cloud.githubusercontent.com/assets/6953063/10461417/2b99db28-71a7-11e5-851e-176150a33df1.png)

![screen shot 2015-10-13 at 12 29 49 pm](https://cloud.githubusercontent.com/assets/6953063/10461430/317d05b0-71a7-11e5-8414-6dd54756e9ac.png)

**Comment by awolfe76** [comment]
@benguhin - do we need to hide the results? Not sure what that's doing is all. 
If people can see the results as they come in, they can interact with them (viewing the map, double checking, etc) rather than waiting for everything. Plus, if we get into one of the slow modes it could be a while ... maybe just have the icon up near the `x of n` counter?
